///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTestProject
{
    /// <summary>
    /// The class representing the NewRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.4")]
    [RepositoryFolder("6419140e-54a8-4dcc-894c-2538db529b4e")]
    public partial class NewRepository : RepoGenBaseFolder
    {
        static NewRepository instance = new NewRepository();
        NewRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the NewRepository element repository.
        /// </summary>
        [RepositoryFolder("6419140e-54a8-4dcc-894c-2538db529b4e")]
        public static NewRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NewRepository() 
            : base("NewRepository", "", null, 30000, false, "6419140e-54a8-4dcc-894c-2538db529b4e", ".\\RepositoryImages\\NewRepository6419140e.rximgres")
        {
            _calculator = new NewRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("32558f68-57d2-4f21-8f93-d0f9c6ea8e29")]
        public virtual NewRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "4.0.4")]
    public partial class NewRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("32558f68-57d2-4f21-8f93-d0f9c6ea8e29")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            NewRepositoryFolders.NumPadFolder _numpad;
            NewRepositoryFolders.OperationsFolder _operations;
            RepoItemInfo _selfInfo;
            RepoItemInfo _textdisplayInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/form[@title='Calculator']", parentFolder, 30000, true, "32558f68-57d2-4f21-8f93-d0f9c6ea8e29", "")
            {
                _numpad = new NewRepositoryFolders.NumPadFolder(this);
                _operations = new NewRepositoryFolders.OperationsFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "32558f68-57d2-4f21-8f93-d0f9c6ea8e29");
                _textdisplayInfo = new RepoItemInfo(this, "TextDisplay", "element/text[@controlid='160']", 30000, null, "ebd2d1bb-64c9-4354-989e-66f39374d31c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32558f68-57d2-4f21-8f93-d0f9c6ea8e29")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32558f68-57d2-4f21-8f93-d0f9c6ea8e29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextDisplay item.
            /// </summary>
            [RepositoryItem("ebd2d1bb-64c9-4354-989e-66f39374d31c")]
            public virtual Ranorex.Text TextDisplay
            {
                get
                {
                    return _textdisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextDisplay item info.
            /// </summary>
            [RepositoryItemInfo("ebd2d1bb-64c9-4354-989e-66f39374d31c")]
            public virtual RepoItemInfo TextDisplayInfo
            {
                get
                {
                    return _textdisplayInfo;
                }
            }

            /// <summary>
            /// The NumPad folder.
            /// </summary>
            [RepositoryFolder("335c6a47-a5a6-4307-8c85-add1e154513b")]
            public virtual NewRepositoryFolders.NumPadFolder NumPad
            {
                get { return _numpad; }
            }

            /// <summary>
            /// The Operations folder.
            /// </summary>
            [RepositoryFolder("4bba23bb-0f8b-4282-84d6-48f106d69255")]
            public virtual NewRepositoryFolders.OperationsFolder Operations
            {
                get { return _operations; }
            }
        }

        /// <summary>
        /// The NumPadFolder folder.
        /// </summary>
        [RepositoryFolder("335c6a47-a5a6-4307-8c85-add1e154513b")]
        public partial class NumPadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _button2Info;
            RepoItemInfo _button3Info;
            RepoItemInfo _button4Info;
            RepoItemInfo _button5Info;
            RepoItemInfo _button6Info;
            RepoItemInfo _button7Info;
            RepoItemInfo _button8Info;
            RepoItemInfo _button9Info;
            RepoItemInfo _button0Info;

            /// <summary>
            /// Creates a new NumPad  folder.
            /// </summary>
            public NumPadFolder(RepoGenBaseFolder parentFolder) :
                    base("NumPad", "", parentFolder, 0, false, "335c6a47-a5a6-4307-8c85-add1e154513b", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='131']", 30000, null, "2b8a8e54-fc0d-4fc2-bec3-d6696f255385");
                _button2Info = new RepoItemInfo(this, "Button2", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='132']", 30000, null, "5a4a0e6d-2dc0-403e-ac10-1be9db71a0fd");
                _button3Info = new RepoItemInfo(this, "Button3", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='133']", 30000, null, "da8807a8-498f-4a23-8f66-a2af18d5b2f3");
                _button4Info = new RepoItemInfo(this, "Button4", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='134']", 30000, null, "5de5fbc6-87fe-4f94-a269-6ed121cfa274");
                _button5Info = new RepoItemInfo(this, "Button5", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='135']", 30000, null, "d4ff07c0-a16a-4167-80da-40d470d5b9cd");
                _button6Info = new RepoItemInfo(this, "Button6", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='136']", 30000, null, "73d14876-ed15-4312-a108-16af37770b6b");
                _button7Info = new RepoItemInfo(this, "Button7", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='137']", 30000, null, "4790d644-1353-4772-bfd2-523bc2d13b3e");
                _button8Info = new RepoItemInfo(this, "Button8", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='138']", 30000, null, "eb2203bf-5095-45ab-84d6-3adc106fd4ae");
                _button9Info = new RepoItemInfo(this, "Button9", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='139']", 30000, null, "654207b7-fcd3-40bf-98a9-e39a5b55f224");
                _button0Info = new RepoItemInfo(this, "Button0", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='130']", 30000, null, "a348d985-7c40-4591-acc2-781dffd49dfd");
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("2b8a8e54-fc0d-4fc2-bec3-d6696f255385")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("2b8a8e54-fc0d-4fc2-bec3-d6696f255385")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("5a4a0e6d-2dc0-403e-ac10-1be9db71a0fd")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("5a4a0e6d-2dc0-403e-ac10-1be9db71a0fd")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button3 item.
            /// </summary>
            [RepositoryItem("da8807a8-498f-4a23-8f66-a2af18d5b2f3")]
            public virtual Ranorex.Button Button3
            {
                get
                {
                    return _button3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button3 item info.
            /// </summary>
            [RepositoryItemInfo("da8807a8-498f-4a23-8f66-a2af18d5b2f3")]
            public virtual RepoItemInfo Button3Info
            {
                get
                {
                    return _button3Info;
                }
            }

            /// <summary>
            /// The Button4 item.
            /// </summary>
            [RepositoryItem("5de5fbc6-87fe-4f94-a269-6ed121cfa274")]
            public virtual Ranorex.Button Button4
            {
                get
                {
                    return _button4Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button4 item info.
            /// </summary>
            [RepositoryItemInfo("5de5fbc6-87fe-4f94-a269-6ed121cfa274")]
            public virtual RepoItemInfo Button4Info
            {
                get
                {
                    return _button4Info;
                }
            }

            /// <summary>
            /// The Button5 item.
            /// </summary>
            [RepositoryItem("d4ff07c0-a16a-4167-80da-40d470d5b9cd")]
            public virtual Ranorex.Button Button5
            {
                get
                {
                    return _button5Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button5 item info.
            /// </summary>
            [RepositoryItemInfo("d4ff07c0-a16a-4167-80da-40d470d5b9cd")]
            public virtual RepoItemInfo Button5Info
            {
                get
                {
                    return _button5Info;
                }
            }

            /// <summary>
            /// The Button6 item.
            /// </summary>
            [RepositoryItem("73d14876-ed15-4312-a108-16af37770b6b")]
            public virtual Ranorex.Button Button6
            {
                get
                {
                    return _button6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button6 item info.
            /// </summary>
            [RepositoryItemInfo("73d14876-ed15-4312-a108-16af37770b6b")]
            public virtual RepoItemInfo Button6Info
            {
                get
                {
                    return _button6Info;
                }
            }

            /// <summary>
            /// The Button7 item.
            /// </summary>
            [RepositoryItem("4790d644-1353-4772-bfd2-523bc2d13b3e")]
            public virtual Ranorex.Button Button7
            {
                get
                {
                    return _button7Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button7 item info.
            /// </summary>
            [RepositoryItemInfo("4790d644-1353-4772-bfd2-523bc2d13b3e")]
            public virtual RepoItemInfo Button7Info
            {
                get
                {
                    return _button7Info;
                }
            }

            /// <summary>
            /// The Button8 item.
            /// </summary>
            [RepositoryItem("eb2203bf-5095-45ab-84d6-3adc106fd4ae")]
            public virtual Ranorex.Button Button8
            {
                get
                {
                    return _button8Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button8 item info.
            /// </summary>
            [RepositoryItemInfo("eb2203bf-5095-45ab-84d6-3adc106fd4ae")]
            public virtual RepoItemInfo Button8Info
            {
                get
                {
                    return _button8Info;
                }
            }

            /// <summary>
            /// The Button9 item.
            /// </summary>
            [RepositoryItem("654207b7-fcd3-40bf-98a9-e39a5b55f224")]
            public virtual Ranorex.Button Button9
            {
                get
                {
                    return _button9Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button9 item info.
            /// </summary>
            [RepositoryItemInfo("654207b7-fcd3-40bf-98a9-e39a5b55f224")]
            public virtual RepoItemInfo Button9Info
            {
                get
                {
                    return _button9Info;
                }
            }

            /// <summary>
            /// The Button0 item.
            /// </summary>
            [RepositoryItem("a348d985-7c40-4591-acc2-781dffd49dfd")]
            public virtual Ranorex.Button Button0
            {
                get
                {
                    return _button0Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button0 item info.
            /// </summary>
            [RepositoryItemInfo("a348d985-7c40-4591-acc2-781dffd49dfd")]
            public virtual RepoItemInfo Button0Info
            {
                get
                {
                    return _button0Info;
                }
            }
        }

        /// <summary>
        /// The OperationsFolder folder.
        /// </summary>
        [RepositoryFolder("4bba23bb-0f8b-4282-84d6-48f106d69255")]
        public partial class OperationsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonmultiplyInfo;
            RepoItemInfo _buttonaddInfo;
            RepoItemInfo _buttonsubtractInfo;
            RepoItemInfo _buttondivideInfo;
            RepoItemInfo _buttonequalsInfo;

            /// <summary>
            /// Creates a new Operations  folder.
            /// </summary>
            public OperationsFolder(RepoGenBaseFolder parentFolder) :
                    base("Operations", "", parentFolder, 0, false, "4bba23bb-0f8b-4282-84d6-48f106d69255", "")
            {
                _buttonmultiplyInfo = new RepoItemInfo(this, "ButtonMultiply", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='92']", 30000, null, "1bd3cb5e-bfcb-4d96-a1d1-a6bd066a0b44");
                _buttonaddInfo = new RepoItemInfo(this, "ButtonAdd", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='93']", 30000, null, "e5426048-0fce-4d87-b3dc-ec5acbff3c64");
                _buttonsubtractInfo = new RepoItemInfo(this, "ButtonSubtract", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='94']", 30000, null, "b7999b55-a280-41f8-8e40-3cc05bb0b6ed");
                _buttondivideInfo = new RepoItemInfo(this, "ButtonDivide", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='91']", 30000, null, "f7866d97-dc94-42c6-9899-bf4684d137fc");
                _buttonequalsInfo = new RepoItemInfo(this, "ButtonEquals", "element/container[@caption='' and @class='#32770' and @instance='1']/button[@text='' and @controlid='121']", 30000, null, "73e651a9-141b-4e68-aaf3-ff651159fc55");
            }

            /// <summary>
            /// The ButtonMultiply item.
            /// </summary>
            [RepositoryItem("1bd3cb5e-bfcb-4d96-a1d1-a6bd066a0b44")]
            public virtual Ranorex.Button ButtonMultiply
            {
                get
                {
                    return _buttonmultiplyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonMultiply item info.
            /// </summary>
            [RepositoryItemInfo("1bd3cb5e-bfcb-4d96-a1d1-a6bd066a0b44")]
            public virtual RepoItemInfo ButtonMultiplyInfo
            {
                get
                {
                    return _buttonmultiplyInfo;
                }
            }

            /// <summary>
            /// The ButtonAdd item.
            /// </summary>
            [RepositoryItem("e5426048-0fce-4d87-b3dc-ec5acbff3c64")]
            public virtual Ranorex.Button ButtonAdd
            {
                get
                {
                    return _buttonaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAdd item info.
            /// </summary>
            [RepositoryItemInfo("e5426048-0fce-4d87-b3dc-ec5acbff3c64")]
            public virtual RepoItemInfo ButtonAddInfo
            {
                get
                {
                    return _buttonaddInfo;
                }
            }

            /// <summary>
            /// The ButtonSubtract item.
            /// </summary>
            [RepositoryItem("b7999b55-a280-41f8-8e40-3cc05bb0b6ed")]
            public virtual Ranorex.Button ButtonSubtract
            {
                get
                {
                    return _buttonsubtractInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSubtract item info.
            /// </summary>
            [RepositoryItemInfo("b7999b55-a280-41f8-8e40-3cc05bb0b6ed")]
            public virtual RepoItemInfo ButtonSubtractInfo
            {
                get
                {
                    return _buttonsubtractInfo;
                }
            }

            /// <summary>
            /// The ButtonDivide item.
            /// </summary>
            [RepositoryItem("f7866d97-dc94-42c6-9899-bf4684d137fc")]
            public virtual Ranorex.Button ButtonDivide
            {
                get
                {
                    return _buttondivideInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDivide item info.
            /// </summary>
            [RepositoryItemInfo("f7866d97-dc94-42c6-9899-bf4684d137fc")]
            public virtual RepoItemInfo ButtonDivideInfo
            {
                get
                {
                    return _buttondivideInfo;
                }
            }

            /// <summary>
            /// The ButtonEquals item.
            /// </summary>
            [RepositoryItem("73e651a9-141b-4e68-aaf3-ff651159fc55")]
            public virtual Ranorex.Button ButtonEquals
            {
                get
                {
                    return _buttonequalsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonEquals item info.
            /// </summary>
            [RepositoryItemInfo("73e651a9-141b-4e68-aaf3-ff651159fc55")]
            public virtual RepoItemInfo ButtonEqualsInfo
            {
                get
                {
                    return _buttonequalsInfo;
                }
            }
        }

    }
}